PackageIdentifier: TIDE.TerminalIDE
PackageVersion: 0.4.1
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/nasazzam/tide/releases/download/v0.4.1/tide-v0.4.1-x86_64-pc-windows-msvc.zip
    InstallerSha256: 8D9CFF62A360B05C7502453323856F6C4D5D1DCFEE3D2B151681AB4B1D2B5D2E
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: tide-editor.exe
        PortableCommandAlias: tide-editor
ManifestType: installer
ManifestVersion: 1.9.0
