PackageIdentifier: TIDE.TerminalIDE
PackageVersion: 0.4.0
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/nasazzam/tide/releases/download/v0.4.0/tide-v0.4.0-x86_64-pc-windows-msvc.zip
    InstallerSha256: B0BD41FE890922B251207ECBE153B57F7DE5B433D1344D6685C37F66F2856B41
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: tide-editor.exe
        PortableCommandAlias: tide-editor
ManifestType: installer
ManifestVersion: 1.9.0
