PackageIdentifier: TIDE.TerminalIDE
PackageVersion: 0.4.3
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/nasazzam/tide/releases/download/v0.4.3/tide-v0.4.3-x86_64-pc-windows-msvc.zip
    InstallerSha256: 8FEB7ECC8B86DD78E2B410D59E06318FCFA52438FDE6C4CFF16D156EB29C9E06
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: tide-editor.exe
        PortableCommandAlias: tide-editor
ManifestType: installer
ManifestVersion: 1.9.0
