PackageIdentifier: TIDE.TerminalIDE
PackageVersion: 0.4.4
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/nasazzam/tide/releases/download/v0.4.4/tide-v0.4.4-x86_64-pc-windows-msvc.zip
    InstallerSha256: D8E6F41BC84CB05D13AFE350726C39C97CCA57FCA80EBC8FF91186180E5EB6E1
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: tide-editor.exe
        PortableCommandAlias: tide-editor
ManifestType: installer
ManifestVersion: 1.9.0
